import {
  parseSlideDocument,
  type Element,
  type SlideDocument,
} from '../src/.sdm/core/schema';
import { analyzeSlideLayout } from '../src/.sdm/core/layoutValidation';
import type { SlideManifestEntry as SlideEntry } from '../src/.sdm/core/slidesManifest';

export interface SdmValidationIo {
  readFile: (projectRelativePath: string) => string | null;
  listFiles: (projectRelativeDir: string) => Array<string>;
}

const SDM_SLIDES_DIR = 'src/data/slides';
const WIDGETS_DIR = 'src/widgets';
const SDM_SLIDE_ID = /^[A-Za-z0-9_-]+$/;

function formatMessage(
  filepath: string,
  code: string,
  elementIds: Array<string>,
  message: string,
): string {
  const ids = elementIds.length > 0 ? ` (${elementIds.join(', ')})` : '';

  return `${filepath} [${code}]${ids}: ${message}`;
}

function collectWidgetModules(
  elements: Array<Element>,
  into: Map<string, string>,
): void {
  for (const element of elements) {
    if (element.type === 'widget') {
      into.set(element.id, element.widget.module);
    } else if (element.type === 'group') {
      collectWidgetModules(element.children, into);
    }
  }
}

function widgetModuleMessages(
  filepath: string,
  document: SlideDocument,
  io: SdmValidationIo,
): Array<string> {
  const modules = new Map<string, string>();
  collectWidgetModules(document.elements, modules);
  if (modules.size === 0) {
    return [];
  }
  const widgetFiles = new Set(
    io.listFiles(WIDGETS_DIR).map((file) => file.replaceAll('\\', '/')),
  );
  const messages: Array<string> = [];
  for (const [elementId, module] of modules) {
    const relative = module.replace(/^\.\/widgets\//, '');
    if (!widgetFiles.has(relative)) {
      messages.push(
        formatMessage(
          filepath,
          'widget-module',
          [elementId],
          `widget module ${module} does not exist under ${WIDGETS_DIR}/. Add the file or fix the module path.`,
        ),
      );
    }
  }

  return messages;
}

export function validateSdmEntries(
  entries: Array<SlideEntry>,
  io: SdmValidationIo,
): Array<string> {
  const messages: Array<string> = [];
  for (const entry of entries) {
    if (!SDM_SLIDE_ID.test(entry.id)) {
      messages.push(
        formatMessage(
          entry.filepath,
          'invalid-id',
          [],
          `slide id "${entry.id}" must contain only letters, numbers, underscores, and hyphens.`,
        ),
      );
      continue;
    }
    const expectedPath = `${SDM_SLIDES_DIR}/${entry.id}.sdm.json`;
    if (entry.filepath !== expectedPath) {
      messages.push(
        formatMessage(
          entry.filepath,
          'manifest-path',
          [],
          `slide "${entry.id}" must use ${expectedPath} so the loader and HMR resolve it.`,
        ),
      );
      continue;
    }
    const raw = io.readFile(entry.filepath);
    if (raw === null) {
      messages.push(
        formatMessage(
          entry.filepath,
          'missing-file',
          [],
          `file not found (referenced by slide "${entry.id}").`,
        ),
      );
      continue;
    }
    let json: unknown;
    try {
      json = JSON.parse(raw);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      messages.push(
        formatMessage(entry.filepath, 'parse-json', [], reason),
      );
      continue;
    }
    const result = parseSlideDocument(json);
    if (!result.ok) {
      if (result.reason === 'unsupportedVersion') {
        messages.push(
          formatMessage(
            entry.filepath,
            'unsupported-version',
            [],
            `document version ${result.version} is newer than this tooling supports; do not edit this file by hand.`,
          ),
        );
      } else {
        for (const issue of result.issues) {
          messages.push(
            formatMessage(
              entry.filepath,
              'schema-invalid',
              [],
              `${issue.path}: ${issue.message}`,
            ),
          );
        }
      }
      continue;
    }
    for (const issue of analyzeSlideLayout(result.document)) {
      messages.push(
        formatMessage(entry.filepath, issue.code, issue.elementIds, issue.message),
      );
    }
    messages.push(...widgetModuleMessages(entry.filepath, result.document, io));
  }

  return messages;
}

export function findOrphanSdmFiles(
  entries: Array<SlideEntry>,
  io: SdmValidationIo,
): Array<string> {
  const referenced = new Set(
    entries
      .filter((entry) => entry.kind === 'sdm')
      .map((entry) => entry.filepath),
  );
  const messages: Array<string> = [];
  for (const file of io.listFiles(SDM_SLIDES_DIR)) {
    const normalized = file.replaceAll('\\', '/');
    if (!normalized.endsWith('.sdm.json')) {
      continue;
    }
    const filepath = `${SDM_SLIDES_DIR}/${normalized}`;
    if (!referenced.has(filepath)) {
      messages.push(
        formatMessage(
          filepath,
          'orphan-file',
          [],
          'not referenced by any manifest entry with kind "sdm". Add a manifest entry or delete the file.',
        ),
      );
    }
  }

  return messages;
}
